### PR TITLE
Added MultiDataQueryProvider for Simplified Data Query Configuration

### PR DESCRIPTION
**Pull request by Sarav-S**
This pull request introduces a `MultiDataQueryProvider` component, simplifying the configuration of nested `DataQueryProvider` instances. Previously, the code required numerous nested `DataQueryProvider` components, making it less readable. With the new `MultiDataQueryProvider`, we can now define a configuration array, making the structure more concise and maintainable.

Changes:

- Added MultiDataQueryProvider component

### Old Approach

```JS
<DataQueryProvider options={{
        ...options,
        resource: 'resource-a'
    }}>
        <DataQueryProvider options={{
            ...options,
            resource: 'resource-b'
        }}>
            <DataQueryProvider options={{
                ...options,
                resource: 'resource-c'
            }}>
                <DataQueryProvider options={{
                    ...options,
                    resource: 'resource-d'
                }}>
                    <ExperiencePageInformation />
            </DataQueryProvider>
        </DataQueryProvider>
    </DataQueryProvider>
</DataQueryProvider>
```

### New Approach

```JS
const config = [
    { ...options, resource: 'resource-a' },
    { ...options, resource: 'resource-b' },
    { ...options, resource: 'resource-c' },
    { ...options, resource: 'resource-d' },
];

<MultiDataQueryProvider options={config}>
    <ExperiencePageInformation />
</MultiDataQueryProvider>
```

### CODE REVIEW

**Comment by ellucianBret** [comment]
@Sarav-S - can you update the version in package.json to 1.1.0?

Thx,
Bret

**Comment by Sarav-S** [comment]
@ellucianBret  I've updated the version number in the package.json file.

**Comment by ellucianBret** [comment]
Can you run "npm i" to update package-lock.json and commit it too?

Thx

**Comment by Sarav-S** [comment]
@ellucianBret I've done the `npm i` and commited the latest changes.

**Pull request merged**
